# Generated by Django 5.0.6 on 2024-05-15 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_remove_todo_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="todo_owner",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
